# Generated by Django 4.1.2 on 2023-06-27 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staking", "__first__"),
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.TextField(default="null")),
                ("input_amount", models.FloatField(default=0)),
                ("output_amount", models.FloatField(default=0)),
                (
                    "output_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ido_id", models.CharField(default="null", max_length=10)),
                ("ewithdraw_status", models.BooleanField(default=False)),
                ("claimed_status", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Ido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        default="default_files/default_file.png",
                        upload_to="account_files/logos/",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="default_files/default_file.png",
                        upload_to="account_files/images/",
                    ),
                ),
                ("token_address", models.CharField(default="null", max_length=50)),
                ("token_symbol", models.CharField(default="null", max_length=3)),
                ("wallet_address", models.CharField(default="null", max_length=50)),
                ("wallet_address_key", models.CharField(default="null", max_length=50)),
                ("name", models.CharField(default="null", max_length=20)),
                ("description", models.TextField(default="null")),
                ("link", models.TextField(default="null")),
                ("listing_price", models.FloatField(default=0)),
                ("presale_price", models.FloatField(default=0)),
                ("soft_cap", models.FloatField(default=0)),
                ("hard_cap", models.FloatField(default=0)),
                ("tier0_min", models.FloatField(default=0)),
                ("tier1_min", models.FloatField(default=0)),
                ("tier2_min", models.FloatField(default=0)),
                ("tier3_min", models.FloatField(default=0)),
                ("tier0_max", models.FloatField(default=0)),
                ("tier1_max", models.FloatField(default=0)),
                ("tier2_max", models.FloatField(default=0)),
                ("tier3_max", models.FloatField(default=0)),
                ("whitelist_limit", models.IntegerField(default=None, null=True)),
                (
                    "whitelist_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "whitelist_stop",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ido_start", models.DateTimeField(default=django.utils.timezone.now)),
                ("ido_stop", models.DateTimeField(default=django.utils.timezone.now)),
                ("allocation_cf_liquidity", models.FloatField(default=0)),
                ("allocation_cf_project", models.FloatField(default=0)),
                ("allocation_pt_liquidity", models.FloatField(default=0)),
                ("allocation_pt_contributors", models.FloatField(default=0)),
                ("allocation_pt_project", models.FloatField(default=0)),
                ("withdraw_project_token_status", models.BooleanField(default=False)),
                (
                    "withdraw_contributed_token_status",
                    models.BooleanField(default=False),
                ),
                ("total_supply", models.FloatField(default=0)),
                ("vesting_duration", models.IntegerField(default=0)),
                ("vesting_amount", models.FloatField(default=0)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "app_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_user.appuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="White",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.TextField(default="null")),
                ("tier", models.CharField(default="null", max_length=20)),
                ("input_amount", models.FloatField(default=0)),
                ("output_amount", models.FloatField(default=0)),
                (
                    "output_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ido_id", models.CharField(default="null", max_length=10)),
                ("ewithdraw_status", models.BooleanField(default=False)),
                ("claimed_status", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="IdoWhiteConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="launchpad.ido"
                    ),
                ),
                (
                    "whitelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="launchpad.white",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdoStakeConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="launchpad.ido"
                    ),
                ),
                (
                    "stake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staking.stake"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdoContributorConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="launchpad.contributor",
                    ),
                ),
                (
                    "ido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="launchpad.ido"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ido",
            name="contributors",
            field=models.ManyToManyField(
                through="launchpad.IdoContributorConnector", to="launchpad.contributor"
            ),
        ),
        migrations.AddField(
            model_name="ido",
            name="stakes",
            field=models.ManyToManyField(
                through="launchpad.IdoStakeConnector", to="staking.stake"
            ),
        ),
        migrations.AddField(
            model_name="ido",
            name="whitelist",
            field=models.ManyToManyField(
                through="launchpad.IdoWhiteConnector", to="launchpad.white"
            ),
        ),
    ]
