# Generated by Django 3.2.16 on 2022-10-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_appuser_passphrase0_appuser_passphrase1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='agency_logo',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='cprofile_status',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='qr_photo',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='rankers',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='ranks',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='whatsapp_link',
        ),
    ]
