# Generated by Django 4.1.2 on 2023-06-27 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("duration", models.IntegerField(default=0)),
                ("returns", models.FloatField(default=0)),
                ("amount_tax", models.FloatField(default=0)),
                ("returns_tax", models.FloatField(default=0)),
                ("total_tax", models.FloatField(default=0)),
                ("payment_hash", models.CharField(default="none", max_length=100)),
                ("payment_status", models.BooleanField(default=False)),
                ("payment_confirmation_status", models.BooleanField(default=False)),
                ("harvest_status", models.BooleanField(default=False)),
                ("due_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_user.appuser",
                    ),
                ),
            ],
        ),
    ]
